apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: node-js-cicd
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/honeysundar/node_js_CICD.git

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./K8S
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: node-js-cicd
  targetNamespace: default
  timeout: 3m0s
  wait: true