name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Kubernetes manifests
        run: |
          #sed -i 's/<TAG>/${{ github.sha }}/g' k8s/deployment.yaml
          kubectl apply -f k8s/

      - name: Commit and push changes
        run: |
          git config --global user.name 'honeysundar'
          git config --global user.email 'honeysundar@gmail.com'
          git add k8s/deployment.yaml
          git commit -m "Update Kubernetes manifests with new image tag"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
