name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Kubernetes manifests
        run: |
          sed -i 's/<TAG>/${{ github.sha }}/g' K8S/deployment.yaml
          #kubectl apply -f K8S/

      - name: Push changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name "honeysundar"
          git config --global user.email "honeysundar@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git add .
          git commit -m "Automated build"
          git push

       
