# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Build and tag Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: 261032345623.dkr.ecr.us-east-1.amazonaws.com/nextjsapp:latest
          
      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo ${{ secrets.KUBECONFIG }} > ~/.kube/config
          kubectl get pod -A

      - name: Deploy to EKS
        run: |
          pwd
          kubectl apply -f deployment.yaml
